### ISSUE TITLE
AttributeError: 'GstSettings' object has no attribute 'use_fallback_for_nic' after upgrading India Compliance from v15.17 to v15.20.1

### ISSUE THREAD

**Issue by Vinothdork** [resilient-tech/india-compliance#3598]
### Information about bug

After upgrading the India Compliance app from version 15.17 to 15.20.1, we encountered the following error while generating the eWay Bill:

![Image](https://github.com/user-attachments/assets/d2d0c1b3-36c7-4c84-8f35-499c8eae70bc)

**AttributeError: 'GstSettings' object has no attribute 'use_fallback_for_nick'
Possible source of error: india_compliance (app)**

This error was not present in version 15.17.0, and appeared immediately after the upgrade.

### Version

ERPNext: v15.58.1 (version-15)

Frappe Framework: v15.66.1 (version-15)

Gmbt: v1.0.1 (gbm_version-2.1.0)

Frappe HR: v15.43.1 (version-15)

India Compliance: v15.17.0 (HEAD)

nxweb_utils: v0.0.1 (master)

WhatsApp Business API Integration: v0.0.1 (master)

Payments: v0.0.1 (version-15)

Qrcode Gen: v1.0.3 (master)

### Relevant log output / Stack trace / Full Error Message.

```shell
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Looks like the site may not have been migrated correctly. Can you see if the issue occurs after `bench --site your_site migrate`

**Comment by sowndharya998** [comment]
I migrated, but I’m still getting the same issue

**Comment by vorasmit** [comment]
Field does exist in the version specified by you. It's a site specific issue / installation issue. Try updating the site if that helps.
